[project]
name = "finvault"
version = "0.1.0"
description = "Personal finance tracker"
readme = "README.md"
authors = [
    { name = "Anand George", email = "anandvgeorge@github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client>=2.200.0",
    "google-auth-httplib2>=0.4.2",
    "google-auth-oauthlib>=1.4.1",
]

[project.scripts]
finvault = "finvault:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/finvault"]
